# Generated by Django 4.1 on 2022-08-09 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0002_project_alter_customusermodel_options_todo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
